[[news]]
date = "2025-09"
content = "I start my PhD at Shanghai Jiao Tong University."

[[news]]
date = "2025-08"
content = "A paper on “Digital Mental Health” has been accepted for publication in SCIENCE CHINA Technological Sciences."

[[news]]
date = "2025-06"
content = "I graduate from Southeast University."
